import type { Loader, LoaderContext } from "astro/loaders"

import { type ReferencePage, referencePages } from "./pages.js"
import { collectRegistry, type Registry } from "./registry.js"

/**
 * The Reference tier as VIRTUAL pages: entries injected straight into Starlight's `docs` collection,
 * with no generated file anywhere on disk.
 *
 * Why no codegen step: a committed generated file is a second copy of a registry, and the moment one
 * exists a reviewer has to decide whether a diff in it is the point of a change or the residue of
 * one. An injected entry is built from the registry on the build that serves it, so the page and the
 * registry cannot be out of step — and it is still an ordinary page, indexed by Pagefind and visible
 * to an `autogenerate` sidebar, because those read the collection rather than the filesystem.
 *
 * `filePath` is mandatory on every entry: the content layer throws a `TypeError` without one, and
 * Starlight's breadcrumbs and autogenerated sidebar both key on the path relative to
 * `src/content/docs`. The paths named here do not exist, and that is the arrangement — the shape is
 * what carries the placement.
 *
 * `editUrl: false` on every entry, because there is no file to edit. Each page names the registry it
 * came from in its last section instead, which is where a change belongs.
 */

/** The docs collection, composed: Starlight's own file loader, then the generated tier. */
export const withReference = (docs: Loader): Loader => ({
  name: "memhtml-docs",
  load: async (context) => {
    // Order is load-bearing. Astro's glob loader deletes every store key it did not touch, so a
    // generated entry written BEFORE it would be swept as a removed file.
    await docs.load(context)
    await loadReference(context)
  }
})

/** The generated tier alone, for a test that drives it against a fake context. */
export const loadReference = async (
  context: LoaderContext,
  registry: Registry = collectRegistry()
): Promise<ReadonlyArray<ReferencePage>> => {
  const pages = referencePages(registry, { base: context.config.base })
  for (const page of pages) {
    const data = await context.parseData({
      id: page.id,
      filePath: page.filePath,
      data: {
        title: page.title,
        description: page.description,
        editUrl: false,
        ...(page.lastUpdated === undefined ? {} : { lastUpdated: page.lastUpdated })
      }
    })
    context.store.set({
      id: page.id,
      data,
      body: page.body,
      filePath: page.filePath,
      digest: context.generateDigest(page.body),
      rendered: await context.renderMarkdown(page.body)
    })
  }
  context.logger.info(`generated ${pages.length} reference pages`)
  return pages
}
