import { RECALL_DISCIPLINE } from "@memhtml/contracts/guidance"
import { describe, expect, it } from "vitest"

import { cliCommand, shellJoin } from "../src/command-line.js"
import {
  renderClaudeImportBlock,
  renderCursorRules,
  renderInstructionBlock
} from "../src/render/block.js"
import type { BinaryLocation } from "../src/types.js"

const BINARY: BinaryLocation = {
  node: "/opt/nodes/24.9.0/bin/node",
  cli: "/opt/memhtml/0.14.0/dist/memhtml.mjs",
  mcp: "/opt/memhtml/0.14.0/dist/memhtml-mcp.mjs",
  version: "0.14.0"
}

const ROOT = "/home/dev/memory"
const CLI = cliCommand(BINARY, true)

const block = (hasMcp: boolean) =>
  renderInstructionBlock({ host: "claude", memhtmlRoot: ROOT, cli: CLI, hasMcp })

const MCP_TOOLS = [
  "memory_search",
  "memory_recall",
  "memory_read",
  "memory_reinforce",
  "memory_write"
]

describe("renderInstructionBlock", () => {
  it("opens with the heading and names the store, both doors, and the manifest", () => {
    const text = block(true)
    expect(text.split("\n")[0]).toBe("## memhtml memory")
    expect(text).toContain(`\`${ROOT}\``)
    for (const tool of MCP_TOOLS) expect(text).toContain(`\`${tool}\``)
    expect(text).toContain(`\`${shellJoin(CLI)} <command>\``)
    expect(text).toContain(`\`${shellJoin(CLI)} manifest\` lists every command`)
  })

  it("names the CLI only, never an MCP tool, when no MCP entry was installed", () => {
    // Scoped to the opening sentence: the discipline paragraphs name both doors by design.
    const sentence = block(false).split("\n")[2] ?? ""
    for (const tool of MCP_TOOLS) expect(sentence).not.toContain(tool)
    expect(sentence).toContain(`\`${shellJoin(CLI)} <command>\``)
    expect(block(true).split("\n")[2] ?? "").toContain("memory_search")
  })

  it("carries every recall-discipline paragraph verbatim", () => {
    /**
     * Verbatim, from `@memhtml/contracts/guidance`, because four surfaces render this text and a
     * paraphrase in one of them is a rule that has quietly changed.
     */
    const text = block(true)
    expect(RECALL_DISCIPLINE).toHaveLength(5)
    for (const paragraph of RECALL_DISCIPLINE) {
      expect(text).toContain(paragraph)
      expect(text.split("\n")).toContain(paragraph)
    }
  })

  it("closes by saying where the text came from and where a human may edit", () => {
    expect(block(true)).toContain(
      "Generated by `memhtml integrations install`; edit outside the markers."
    )
  })

  it("stays under forty lines, because it is in context every session", () => {
    for (const hasMcp of [true, false]) {
      expect(block(hasMcp).split("\n").length).toBeLessThan(40)
    }
  })

  it("renders the same body for every host today", () => {
    const bodies = (["claude", "codex", "cursor", "opencode"] as const).map((host) =>
      renderInstructionBlock({ host, memhtmlRoot: ROOT, cli: CLI, hasMcp: true })
    )
    expect(new Set(bodies).size).toBe(1)
  })
})

describe("renderCursorRules", () => {
  it("wraps the block in .mdc frontmatter that always applies", () => {
    const text = renderCursorRules(block(true))
    const lines = text.split("\n")
    expect(lines[0]).toBe("---")
    expect(lines[1]).toBe(
      'description: "memhtml long-term memory: recall before answering, reinforce after use"'
    )
    expect(lines[2]).toBe("alwaysApply: true")
    expect(lines[3]).toBe("---")
    expect(text).toContain(block(true))
  })

  it("quotes the description, since a plain YAML scalar cannot hold a colon-space", () => {
    /** `description: memhtml long-term memory: recall …` is a YAML error, not a rule Cursor would read. */
    const frontmatter = renderCursorRules(block(true)).split("---")[1] ?? ""
    for (const line of frontmatter.trim().split("\n")) {
      const value = line.slice(line.indexOf(":") + 1).trim()
      if (value.includes(": ")) expect(value.startsWith('"')).toBe(true)
    }
  })
})

describe("renderClaudeImportBlock", () => {
  it("is Claude Code's import syntax on its own line, not a Markdown link", () => {
    expect(renderClaudeImportBlock()).toBe("@AGENTS.md\n")
    expect(renderClaudeImportBlock()).not.toContain("](")
  })
})
