/**
 * The instruction block: the prose a host's own instruction file carries so the agent knows it HAS a
 * memory store before any tool call happens.
 *
 * The discipline paragraphs are imported verbatim from `@memhtml/contracts/guidance`, never restated
 * here. Four surfaces render that text — the manifest's `recall-discipline` guide topic, the MCP
 * retrieval tools' descriptions, this block, and the skill — and a hand-written copy in any one of them
 * would drift the first time a rule moved.
 *
 * What this module renders is only the body. The fence markers, the file it lands in
 * (`~/.claude/CLAUDE.md`, `~/.codex/AGENTS.md`, a project `AGENTS.md`), and the merge belong to the
 * primitives layer, so the same body can be placed in whichever file a host reads.
 */

import { RECALL_DISCIPLINE } from "@memhtml/contracts/guidance"

import { shellJoin } from "../command-line.js"
import type { CommandLine, HostId } from "../types.js"

export interface InstructionBlockOptions {
  /**
   * The host this block is rendered for. The body is byte-identical across the four hosts today, and the
   * parameter is here so a host-specific line has exactly one place to land rather than being spliced in
   * by whoever needs it first.
   */
  readonly host: HostId
  /** The store, absolute, named in the prose so the agent can see which repo it is remembering into. */
  readonly memhtmlRoot: string
  /** How this host invokes the CLI, rendered as the shell string an operator could paste. */
  readonly cli: CommandLine
  /** Whether an MCP entry was installed; when false the block names the CLI only. */
  readonly hasMcp: boolean
}

/** The MCP tools the block points at, in the order an agent meets them. */
const MCP_TOOLS = [
  "memory_search",
  "memory_recall",
  "memory_read",
  "memory_reinforce",
  "memory_write"
]

/**
 * The block body: what the store is, how to reach it, the five discipline rules, and where the text came
 * from. Short by construction — under forty lines — because it is prepended to every session on hosts
 * that read their instruction file eagerly.
 */
export const renderInstructionBlock = (opts: InstructionBlockOptions): string => {
  const cli = shellJoin(opts.cli)
  const doors = opts.hasMcp
    ? `the MCP tools ${MCP_TOOLS.map((tool) => `\`${tool}\``).join(", ")} and the CLI \`${cli} <command>\``
    : `the CLI \`${cli} <command>\``
  return [
    "## memhtml memory",
    "",
    `You have a long-term memory store at \`${opts.memhtmlRoot}\`, reachable through ${doors} (\`${cli} manifest\` lists every command).`,
    "",
    ...RECALL_DISCIPLINE.flatMap((paragraph) => [paragraph, ""]),
    "Generated by `memhtml integrations install`; edit outside the markers.",
    ""
  ].join("\n")
}

/**
 * The Cursor rules file. Cursor reads `.cursor/rules/*.mdc` and IGNORES a plain `.md`, and only
 * `alwaysApply: true` puts a rule in front of every request rather than waiting for its description to
 * match. The description is quoted because it contains a colon-space, which a plain YAML scalar cannot.
 */
export const renderCursorRules = (block: string): string =>
  [
    "---",
    'description: "memhtml long-term memory: recall before answering, reinforce after use"',
    "alwaysApply: true",
    "---",
    "",
    block
  ].join("\n")

/**
 * The body for a project `CLAUDE.md` when the block itself lives in `AGENTS.md`.
 *
 * Claude Code does not read `AGENTS.md`; it reads `CLAUDE.md`, where a line beginning `@` is an IMPORT
 * (resolved up to four hops deep). A Markdown link would render as text the model may or may not follow,
 * which is why this is `@AGENTS.md` and not `[AGENTS.md](./AGENTS.md)`.
 */
export const renderClaudeImportBlock = (): string => "@AGENTS.md\n"
