/**
 * The OpenCode plugin, rendered as a self-contained ESM module.
 *
 * OpenCode has no hooks file: its hook system IS a plugin, a JS module in
 * `~/.config/opencode/plugins/` exporting a factory that returns typed handlers (vendor docs read
 * 2026-09-13). So this is the one host where the installer writes CODE, and two rules follow from that.
 *
 * It imports `node:child_process` and NOTHING else — not `@memhtml/integrations`, not
 * `@opencode-ai/plugin`, not the memhtml package. A plugin that imported memhtml would break the moment
 * the toolchain moved the package, and OpenCode loads plugins at startup, so the failure would be a dead
 * session rather than a missing memory. Instead the recorded command line is baked in as a literal and
 * the plugin shells out to the same `memhtml hook` engine every other host calls.
 *
 * And it is fail-open in every direction: one 1500 ms bound per call, any spawn error, non-zero exit, or
 * timeout resolves to an empty string, and an empty string pushes nothing. A memory store that is down
 * costs the session nothing.
 */

import type { HookCommandOptions } from "../command-line.js"
import { hookCommand } from "../command-line.js"
import type { BinaryLocation, HookEvent, HookMode } from "../types.js"

/** The file name inside the host's plugins directory. */
export const OPENCODE_PLUGIN_FILE = "memhtml.js"

/** The per-call wall clock the generated plugin allows one hook. */
const PLUGIN_TIMEOUT_MS = 1500

/**
 * Render the plugin for one install.
 *
 * `mode` prunes handlers rather than flags them off: `all` wires the per-message recall, the compaction
 * context, and the idle indexer; `session` drops the per-message recall (the compaction and idle
 * handlers remain, since neither runs per turn); `none` renders NOTHING — the empty string, so the
 * installer writes no plugin file at all. The idle handler exists only when a transcript root is known,
 * because indexing needs something to read.
 */
export const renderOpenCodePlugin = (
  binary: BinaryLocation,
  bare: boolean,
  mode: HookMode,
  opts: HookCommandOptions
): string => {
  if (mode === "none") return ""
  const line = (event: HookEvent) => hookCommand(binary, bare, event, "opencode", opts)
  const session = line("session-start")
  const wantsPrompt = mode === "all"
  const wantsIdle = opts.traceRoot !== undefined
  const root = opts.memhtmlRoot.replaceAll("\n", " ")

  const lines: Array<string> = [
    "// Generated by `memhtml integrations install`. Do not edit: the next install overwrites this file.",
    `// It wires this OpenCode session to the memhtml memory store at ${root}, by running`,
    "// `memhtml hook` and pushing what it prints into the conversation. It imports nothing from memhtml,",
    "// so a moved or upgraded memhtml cannot stop OpenCode from starting.",
    'import { execFile } from "node:child_process"',
    "",
    `const TIMEOUT_MS = ${PLUGIN_TIMEOUT_MS}`,
    `const COMMAND = ${JSON.stringify(session.command)}`
  ]
  if (wantsPrompt) {
    lines.push(`const PROMPT_ARGS = ${JSON.stringify([...line("user-prompt-submit").args])}`)
  }
  lines.push(`const SESSION_ARGS = ${JSON.stringify([...session.args])}`)
  if (wantsIdle) {
    lines.push(`const IDLE_ARGS = ${JSON.stringify([...line("session-end").args])}`)
  }
  lines.push(
    "",
    "// Every failure mode collapses to an empty string: no output means no change to the session.",
    "const run = (args, payload) =>",
    "  new Promise((resolve) => {",
    "    let child",
    "    try {",
    "      child = execFile(",
    "        COMMAND,",
    "        args,",
    "        { timeout: TIMEOUT_MS, maxBuffer: 1024 * 1024 },",
    '        (error, stdout) => resolve(error ? "" : String(stdout ?? "").trim())',
    "      )",
    "    } catch {",
    '      resolve("")',
    "      return",
    "    }",
    '    child.on("error", () => resolve(""))',
    "    if (child.stdin) {",
    '      child.stdin.on("error", () => {})',
    "      child.stdin.end(JSON.stringify(payload))",
    "    }",
    "  })",
    "",
    "const textOf = (message) => {",
    "  const parts = message && Array.isArray(message.parts) ? message.parts : []",
    "  return parts",
    '    .filter((part) => part && part.type === "text" && typeof part.text === "string")',
    "    .map((part) => part.text)",
    '    .join("\\n")',
    "    .trim()",
    "}",
    "",
    "export const MemhtmlPlugin = async ({ directory }) => ({"
  )
  const handlers: Array<Array<string>> = []
  if (wantsPrompt) {
    handlers.push([
      '  "chat.message": async (input, output) => {',
      "    const prompt = textOf(output) || textOf(input)",
      "    if (prompt.length === 0) return",
      "    const text = await run(PROMPT_ARGS, { prompt, cwd: directory })",
      "    if (text.length === 0 || !output || !Array.isArray(output.parts)) return",
      '    output.parts.push({ type: "text", text })',
      "  }"
    ])
  }
  handlers.push([
    '  "experimental.session.compacting": async (input, output) => {',
    "    const text = await run(SESSION_ARGS, { cwd: directory })",
    "    if (text.length === 0 || !output || !Array.isArray(output.context)) return",
    "    output.context.push(text)",
    "  }"
  ])
  if (wantsIdle) {
    handlers.push([
      "  event: async ({ event }) => {",
      '    if (!event || event.type !== "session.idle") return',
      "    await run(IDLE_ARGS, { cwd: directory })",
      "  }"
    ])
  }
  handlers.forEach((handler, index) => {
    const last = index === handlers.length - 1
    handler.forEach((text, position) => {
      lines.push(!last && position === handler.length - 1 ? `${text},` : text)
    })
  })
  lines.push("})", "")
  return lines.join("\n")
}
