import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"

import { InvalidMemory, StorageFailure } from "@memhtml/contracts/errors"
import { Effect } from "effect"

import { COMMANDS, GLOBAL_FLAGS, GUIDE } from "./commands.js"
import { CONFIG_VARS } from "./config.js"
import { API_VERSION, ERROR_CODES, EXIT_OK, EXIT_RUNTIME, EXIT_USAGE } from "./envelope.js"

/**
 * `AGENTS.md`, generated from the same `COMMANDS` array that drives parsing.
 *
 * Generated rather than written, so the doc cannot describe a flag the binary does not accept. A test
 * checks the committed file against a fresh render, and `memhtml agents-doc --check` runs the same
 * comparison as a command, so the drift is catchable in CI and fixable in one call.
 *
 * The rendering is deterministic to the byte: no timestamp, no version of anything but the CLI
 * itself, no iteration over an unordered structure. A generator whose output moved on every run
 * would make the drift check useless.
 */

/** Where the doc lives by default: the repo root, next to `package.json`. */
export const AGENTS_DOC_PATH = "AGENTS.md"

const escapeCell = (text: string): string => text.replaceAll("|", "\\|")

const flagCell = (flags: ReadonlyArray<{ readonly name: string; readonly required?: boolean }>) =>
  flags.length === 0
    ? "—"
    : flags
        .map((flag) => (flag.required === true ? `\`--${flag.name}\`*` : `\`--${flag.name}\``))
        .join(" ")

const argCell = (args: ReadonlyArray<{ readonly name: string; readonly required: boolean }>) =>
  args.length === 0
    ? "—"
    : args.map((arg) => (arg.required ? `<${arg.name}>` : `[${arg.name}]`)).join(" ")

/**
 * The guide blocks as Markdown, each under its own topic heading.
 *
 * The topic is the heading and it is code-quoted, so the key an agent reads from
 * `memhtml manifest`'s `guide[].topic` is greppable in this file. The two projections of one array
 * must name their blocks identically, or the reader cannot cross-reference them.
 *
 * A body line beginning with `{` becomes a fenced JSON block. The `when-to-batch` block carries an
 * example op line an agent copies, and that example is only useful if it survives the trip through
 * Markdown unwrapped and unescaped. The rule is derived from the content's own shape rather than
 * from a per-block flag, so a second example added to a second block needs no edit here.
 */
const guideLines = (): ReadonlyArray<string> => {
  const lines: Array<string> = ["## Guide", ""]
  for (const block of GUIDE) {
    lines.push(`### \`${block.topic}\``)
    lines.push("")
    for (const paragraph of block.body.split("\n")) {
      if (paragraph.startsWith("{")) {
        lines.push("```json")
        lines.push(paragraph)
        lines.push("```")
      } else {
        lines.push(paragraph)
      }
      lines.push("")
    }
  }
  return lines
}

/** The whole document, as bytes. */
export const renderAgentsDoc = (): string => {
  const lines: Array<string> = []

  lines.push("<!-- Generated by `memhtml agents-doc`. Edit `apps/cli/src/commands.ts` instead. -->")
  lines.push("")
  lines.push("# `memhtml` — agent instructions")
  lines.push("")
  lines.push(
    "`memhtml` is the CLI over a git-backed memory repo. Every command writes exactly ONE JSON envelope"
  )
  lines.push("to stdout and nothing else; logs go to stderr.")
  lines.push("")
  lines.push("## The envelope")
  lines.push("")
  lines.push("```json")
  lines.push(`{ "apiVersion": "${API_VERSION}", "type": "<response type>", "data": { } }`)
  lines.push("```")
  lines.push("")
  lines.push("A failure is a different shape, and `code` is what you branch on:")
  lines.push("")
  lines.push("```json")
  lines.push(
    `{ "apiVersion": "${API_VERSION}", "error": "<prose>", "code": "<ERROR_CODE>", "suggestions": ["<command>"] }`
  )
  lines.push("```")
  lines.push("")
  lines.push(
    "Never branch on the `error` string — it changes freely as wording improves. `code` and `type`"
  )
  lines.push("are append-only: a shipped value never changes meaning and is never removed.")
  lines.push("")
  lines.push(
    `Exit codes: **${EXIT_OK}** success, **${EXIT_USAGE}** usage error (unknown command, bad flag,`
  )
  lines.push(`missing argument), **${EXIT_RUNTIME}** runtime failure.`)
  lines.push("")
  lines.push("## Start here")
  lines.push("")
  lines.push(
    "`memhtml manifest` is the first call to make. It answers with every command, argument, flag,"
  )
  lines.push(
    "response type, and error code this binary accepts — and it answers on a machine with no repo,"
  )
  lines.push("no database, and no credentials, so it is also the liveness check.")
  lines.push("")
  /**
   * The guide goes before the command table, because it is what makes the table mean something. The
   * three write doors, when to batch, and the authoring XOR are decisions an agent makes before it
   * picks a command. Rendered from the same `GUIDE` array `memhtml manifest` returns, so an agent that
   * read the doc and an agent that called the binary got the same words.
   */
  lines.push(...guideLines())
  lines.push("## Global flags")
  lines.push("")
  lines.push("| Flag | Type | Default | Meaning |")
  lines.push("|---|---|---|---|")
  for (const flag of GLOBAL_FLAGS) {
    lines.push(
      `| \`--${flag.name}\` | ${flag.type} | ${flag.default === "" ? "—" : String(flag.default)} | ${escapeCell(flag.description)} |`
    )
  }
  lines.push("")
  lines.push("## Commands")
  lines.push("")
  lines.push("`<required>` `[optional]`; a flag marked `*` is required.")
  lines.push("")
  lines.push("| Command | Arguments | Flags | Response type |")
  lines.push("|---|---|---|---|")
  for (const command of COMMANDS) {
    lines.push(
      `| \`memhtml ${command.name}\` | ${argCell(command.args)} | ${flagCell(command.flags)} | ${command.responseTypes.map((type) => `\`${type}\``).join(", ")} |`
    )
  }
  lines.push("")

  for (const command of COMMANDS) {
    lines.push(`### \`memhtml ${command.name}\``)
    lines.push("")
    lines.push(command.summary)
    lines.push("")
    if (command.args.length > 0) {
      for (const arg of command.args) {
        lines.push(
          `- \`${arg.required ? `<${arg.name}>` : `[${arg.name}]`}\` — ${escapeCell(arg.description)}`
        )
      }
      lines.push("")
    }
    if (command.flags.length > 0) {
      for (const flag of command.flags) {
        const suffix = [
          flag.required === true ? "**required**" : undefined,
          flag.repeatable === true ? "repeatable" : undefined,
          flag.default === undefined ? undefined : `default \`${String(flag.default)}\``,
          flag.values === undefined
            ? undefined
            : `one of: ${flag.values.map((value) => `\`${value}\``).join(", ")}`
        ]
          .filter((part) => part !== undefined)
          .join("; ")
        lines.push(
          `- \`--${flag.name}\` (${flag.type}) — ${escapeCell(flag.description)}${suffix === "" ? "" : ` _(${suffix})_`}`
        )
      }
      lines.push("")
    }
  }

  lines.push("## Error codes")
  lines.push("")
  for (const code of ERROR_CODES) lines.push(`- \`${code}\``)
  lines.push("")
  lines.push("## Configuration")
  lines.push("")
  lines.push("| Variable | Default | Meaning |")
  lines.push("|---|---|---|")
  for (const variable of CONFIG_VARS) {
    lines.push(
      `| \`${variable.name}\` | ${variable.fallback === null ? "—" : `\`${variable.fallback}\``} | ${escapeCell(variable.description)} |`
    )
  }
  lines.push("")

  return `${lines.join("\n")}\n`
}

/** What a generate-or-check pass produced. */
export interface AgentsDocResult {
  readonly path: string
  readonly bytes: number
  /** True when the file on disk already matched. `--check` fails when this is false. */
  readonly inSync: boolean
  /** True when this call wrote the file. False under `--check`, which never writes. */
  readonly written: boolean
}

/**
 * Write the doc, or compare it and fail on drift.
 *
 * `--check` is the CI form and it writes nothing. A check that fixed the drift it found would make
 * a green pipeline out of an uncommitted change.
 */
export const runAgentsDoc = (options: {
  readonly check: boolean
  readonly out?: string | undefined
}): Effect.Effect<AgentsDocResult, InvalidMemory | StorageFailure> =>
  Effect.gen(function* () {
    const path = resolve(options.out ?? AGENTS_DOC_PATH)
    const rendered = renderAgentsDoc()

    const existing = yield* Effect.tryPromise({
      try: () => readFile(path, "utf8"),
      catch: () => null
    }).pipe(Effect.orElseSucceed(() => null))

    const inSync = existing === rendered

    if (options.check) {
      if (!inSync) {
        return yield* Effect.fail(
          InvalidMemory.make({
            reason:
              existing === null
                ? `${path} is missing; run \`memhtml agents-doc\``
                : `${path} is out of date; run \`memhtml agents-doc\``
          })
        )
      }
      return { path, bytes: rendered.length, inSync, written: false }
    }

    if (inSync) return { path, bytes: rendered.length, inSync, written: false }

    yield* Effect.tryPromise({
      try: () => writeFile(path, rendered, "utf8"),
      catch: () => StorageFailure.make({ operation: `agents-doc.write:${path}` })
    })
    return { path, bytes: rendered.length, inSync: false, written: true }
  })
